### ISSUE TITLE
Python f strings

### ISSUE THREAD

**Issue by JacobHA** [amadeus4dev/amadeus-smart-flight-search-django#8]
I would suggest using python's f string implementation to make code more readable. For instance 

"https://s1.apideeplink.com/images/airlines/" + carrier_code + ".png"
f"https://s1.apideeplink.com/images/airlines/{carrier_code}.png"

and 

str(index) + 'firstFlightDepartureAirport'
f"{index}firstFlightDepartureAirport'

in flight.py file.

**Comment by JacobHA** [comment]
def CurrentVec (T_f,nt):
    tvec = np.linspace(0,T_f,nt+1)      #Vector of the x_values of the graph
    ivec = np.zeros(tvec.size)          #Vector of the current at
corresponding time
    i_dot_vec = np.zeros(tvec.size)
    ivec[0] = i_0
    i_dot_vec[0] = i_dot_0
    for j in range(1,tvec.size):        #For each time step looping to find
the curent flow
        delta_t = tvec[j] - tvec[j-1]
        Current_double_dot =,
        i_double_dot(R,L,C,Vm,w,tvec[j-1],ivec[j-1],i_dot_vec[j-1])
        i_dot_vec[j] =,
        Current_double_dot*delta_t + i_dot_vec[j-1]
        ivec[j] = i_dot_vec[j]*delta_t + ivec[j-1]
    return [tvec,ivec]

**Comment by tsolakoua** [comment]
Hello @JacobHA, thank you for your recommendation about using `f-strings`. 
What is the method `def CurrentVec (T_f,nt):` about you posted on your second comment?

**Comment by JacobHA** [comment]
Hi Anna, please ignore this method "CurrentVec..." this was an accident.
Regarding the f-strings: I'm glad you will take up my recommendation. They
are overall faster and I believe more readable. They are also now enforced
in PEP styling which may or may not concern you (to be fair, I do not have
tremendous regard for it as my personal code is not at production level).
Also, one other cool thing about f-strings is that you can do operations
within them, for instance things like f'The sum is {x+y}' or indexing such
as f'the zeroth position of list L contains {L[0]}'

**Comment by tsolakoua** [comment]
Thank you @JacobHA for your feedback! Already did the changes using f-strings!
